/// Datos de prueba iniciales basados en los esquemas de Supabase y mockups oficiales de FundAPP
class MockData {
  MockData._();

  static const Map<String, dynamic> sampleUser = {
    'id': 'u101-uuid-biosferas-voluntario',
    'nombres': 'Luis Fernando',
    'apellidos': 'Pérez Gómez',
    'correo': 'luis@correo.com',
    'fecha_nacimiento': '2001-05-02',
    'telefono': '+57 312 456 7890',
    'rol': 'voluntario',
    'created_at': '2025-01-15T09:00:00Z',
    'meta_anual_horas': 20,
    'horas_acumuladas': 0,
    'total_certificados': 0,
    'total_donaciones': 0.0,
  };

  static const List<Map<String, dynamic>> sampleActivities = [
    {
      'id': 'act-001',
      'titulo': 'Reforestación Río Bosque',
      'descripcion': 'Jornada de siembra de 300 especies nativas junto a la comunidad local para proteger la cuenca hídrica.',
      'categoria': 'Reforestación',
      'fecha': '2026-09-05',
      'hora': '08:00 AM',
      'duracion_horas': 4,
      'cupos_totales': 30,
      'cupos_ocupados': 18,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Vereda El Bosque, Cuenca Alta',
      'latitud': 4.711000,
      'longitud': -74.072100,
      'radio_permitido_metros': 120,
      'puntos_impacto': 150,
      'tags': ['Siembra', 'Bosque', 'Comunidad'],
      'imagen_url': 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800',
    },
    {
      'id': 'act-002',
      'titulo': 'Jornada de Reciclaje Urbano',
      'descripcion': 'Separación y recolección de materiales reciclables en parques zonales para fomentar la economía circular con recicladores de oficio.',
      'categoria': 'Reciclaje',
      'fecha': '2026-09-11',
      'hora': '09:00 AM',
      'duracion_horas': 3,
      'cupos_totales': 20,
      'cupos_ocupados': 15,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Parque Principal Simón Bolívar',
      'latitud': 4.658300,
      'longitud': -74.093900,
      'radio_permitido_metros': 100,
      'puntos_impacto': 100,
      'tags': ['Reciclaje', 'Ciudad', 'CeroBasura'],
      'imagen_url': 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800',
    },
    {
      'id': 'act-003',
      'titulo': 'Limpieza de Humedal Córdoba',
      'descripcion': 'Recuperación ambiental del ecosistema acuático, retiro de residuos sólidos y censo básico de aves migratorias.',
      'categoria': 'Conservación',
      'fecha': '2026-09-19',
      'hora': '07:30 AM',
      'duracion_horas': 5,
      'cupos_totales': 25,
      'cupos_ocupados': 25,
      'estado_cupos': 'lleno',
      'ubicacion_nombre': 'Humedal Córdoba, Entrada Norte',
      'latitud': 4.701200,
      'longitud': -74.075400,
      'radio_permitido_metros': 150,
      'puntos_impacto': 200,
      'tags': ['Humedal', 'Aves', 'Conservación'],
      'imagen_url': 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800',
    },
    {
      'id': 'act-004',
      'titulo': 'Educación Ambiental Escolar',
      'descripcion': 'Talleres interactivos con niños de primaria sobre cuidado del agua y huertas caseras sostenibles.',
      'categoria': 'Educación',
      'fecha': '2026-09-25',
      'hora': '10:00 AM',
      'duracion_horas': 2,
      'cupos_totales': 15,
      'cupos_ocupados': 5,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Colegio Ecológico San Rafael',
      'latitud': 4.675000,
      'longitud': -74.060000,
      'radio_permitido_metros': 80,
      'puntos_impacto': 80,
      'tags': ['Talleres', 'Niños', 'Huertas'],
      'imagen_url': 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800',
    },
    {
      'id': 'act-005',
      'titulo': 'Siembra de Frailejones en Páramo',
      'descripcion': 'Restauración ecológica de alta montaña sembrando plántulas de frailejón para salvaguardar las fábricas naturales de agua.',
      'categoria': 'Reforestación',
      'fecha': '2026-10-03',
      'hora': '06:30 AM',
      'duracion_horas': 6,
      'cupos_totales': 20,
      'cupos_ocupados': 12,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Páramo de Sumapaz, Sector Laguna',
      'latitud': 4.250000,
      'longitud': -74.250000,
      'radio_permitido_metros': 200,
      'puntos_impacto': 250,
      'tags': ['Páramo', 'Agua', 'Frailejones'],
      'imagen_url': 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    },
    {
      'id': 'act-006',
      'titulo': 'Censo y Monitoreo de Aves Silvestres',
      'descripcion': 'Avistamiento matutino y registro biológico de aves en el sendero ecológico para la base de datos de biodiversidad.',
      'categoria': 'Conservación',
      'fecha': '2026-10-12',
      'hora': '06:00 AM',
      'duracion_horas': 3,
      'cupos_totales': 15,
      'cupos_ocupados': 10,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Reserva Natural Cerros Orientales',
      'latitud': 4.610000,
      'longitud': -74.050000,
      'radio_permitido_metros': 100,
      'puntos_impacto': 120,
      'tags': ['Aves', 'BioCenso', 'Fauna'],
      'imagen_url': 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=800',
    },
  ];

  static const List<Map<String, dynamic>> sampleCertificates = [];

  static const List<Map<String, dynamic>> sampleBadges = [
    {
      'id': 'badge-01',
      'nombre': 'Primeros pasos',
      'descripcion': 'Completar 1 actividad con tracking activo',
      'icono': 'directions_walk',
      'obtenida': true,
      'fecha_obtenida': '2026-08-15',
      'categoria': 'Esfuerzo Físico',
    },
    {
      'id': 'badge-02',
      'nombre': 'Caminante constante',
      'descripcion': '3 actividades seguidas con +2.000 pasos',
      'icono': 'nordic_walking',
      'obtenida': true,
      'fecha_obtenida': '2026-08-28',
      'categoria': 'Esfuerzo Físico',
    },
    {
      'id': 'badge-03',
      'nombre': 'Jornada intensa',
      'descripcion': 'Superar 8.000 pasos en una sola actividad',
      'icono': 'local_fire_department',
      'obtenida': false,
      'fecha_obtenida': null,
      'categoria': 'Esfuerzo Físico',
    },
  ];
}
