/// Datos de prueba iniciales basados en los esquemas de Supabase y mockups oficiales de FundAPP
class MockData {
  MockData._();

  static const Map<String, dynamic> sampleUser = {
    'id': 'u101-uuid-biosferas-voluntario',
    'nombres': 'Luis Fernando',
    'apellidos': 'Pérez Gómez',
    'correo': 'luis@correo.com',
    'fecha_nacimiento': '2001-05-02',
    'telefono': '+57 312 456 7890',
    'rol': 'voluntario',
    'created_at': '2025-01-15T09:00:00Z',
    'meta_anual_horas': 20,
    'horas_acumuladas': 0,
    'total_certificados': 0,
    'total_donaciones': 0.0,
  };

  static const List<Map<String, dynamic>> sampleActivities = [
    {
      'id': 'act-001',
      'titulo': 'Reforestación Río Bosque',
      'descripcion': 'Jornada de siembra de especies nativas junto a la comunidad local. Se proveen herramientas y refrigerio. Tu aporte ayuda a proteger la cuenca hídrica.',
      'categoria': 'Reforestación',
      'fecha': '2026-09-05',
      'hora': '08:00 AM',
      'duracion_horas': 4,
      'cupos_totales': 30,
      'cupos_ocupados': 18,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Vereda El Bosque, Cuenca Alta',
      'latitud': 4.711000,
      'longitud': -74.072100,
      'radio_permitido_metros': 120,
      'puntos_impacto': 150,
      'tags': ['Siembra', 'Bosque', 'Comunidad'],
      'imagen_url': 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600',
    },
    {
      'id': 'act-002',
      'titulo': 'Jornada de Reciclaje Urbano',
      'descripcion': 'Separación y recolección de materiales reciclables en parques zonales para fomentar la economía circular con recicladores de oficio.',
      'categoria': 'Reciclaje',
      'fecha': '2026-09-11',
      'hora': '09:00 AM',
      'duracion_horas': 3,
      'cupos_totales': 20,
      'cupos_ocupados': 15,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Parque Principal Simón Bolívar',
      'latitud': 4.658300,
      'longitud': -74.093900,
      'radio_permitido_metros': 100,
      'puntos_impacto': 100,
      'tags': ['Reciclaje', 'Ciudad', 'CeroBasura'],
      'imagen_url': 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    },
    {
      'id': 'act-003',
      'titulo': 'Limpieza de Humedal Córdoba',
      'descripcion': 'Recuperación ambiental del ecosistema acuático, retiro de residuos sólidos y censo básico de aves migratorias.',
      'categoria': 'Conservación',
      'fecha': '2026-09-19',
      'hora': '07:30 AM',
      'duracion_horas': 5,
      'cupos_totales': 25,
      'cupos_ocupados': 25,
      'estado_cupos': 'lleno',
      'ubicacion_nombre': 'Humedal Córdoba, Entrada Norte',
      'latitud': 4.701200,
      'longitud': -74.075400,
      'radio_permitido_metros': 150,
      'puntos_impacto': 200,
      'tags': ['Humedal', 'Aves', 'Conservación'],
      'imagen_url': 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=600',
    },
    {
      'id': 'act-004',
      'titulo': 'Educación Ambiental Escolar',
      'descripcion': 'Talleres interactivos con niños de primaria sobre cuidado del agua y huertas caseras sostenibles.',
      'categoria': 'Educación',
      'fecha': '2026-09-25',
      'hora': '10:00 AM',
      'duracion_horas': 2,
      'cupos_totales': 15,
      'cupos_ocupados': 5,
      'estado_cupos': 'disponible',
      'ubicacion_nombre': 'Colegio Ecológico San Rafael',
      'latitud': 4.675000,
      'longitud': -74.060000,
      'radio_permitido_metros': 80,
      'puntos_impacto': 80,
      'tags': ['Talleres', 'Niños', 'Huertas'],
      'imagen_url': 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600',
    },
  ];

  static const List<Map<String, dynamic>> sampleCertificates = [
    {
      'id': 'cert-001',
      'tipo': 'voluntariado',
      'titulo': 'Certificado de Voluntariado',
      'actividad_titulo': 'Reforestación Río Bosque',
      'horas': 14,
      'fecha_emision': '2026-08-15',
      'estado': 'aprobado',
      'codigo_verificacion': 'FB-VOL-2026-0892',
      'firmado_por': 'Dra. Elena Ramos - Directora Ejecutiva',
      'destinatario': 'Luis Fernando Pérez Gómez',
      'documento_identidad': '1.098.765.432',
    },
    {
      'id': 'cert-002',
      'tipo': 'donacion',
      'titulo': 'Certificado de Donación',
      'actividad_titulo': 'Aporte Proyecto Cuencas Vivas',
      'monto': 70000.0,
      'fecha_emision': '2026-07-28',
      'estado': 'aprobado',
      'codigo_verificacion': 'FB-DON-2026-0411',
      'firmado_por': 'Carlos Mendoza - Tesorería Fundación',
      'destinatario': 'Luis Fernando Pérez Gómez',
      'documento_identidad': '1.098.765.432',
    },
    {
      'id': 'cert-003',
      'tipo': 'voluntariado',
      'titulo': 'Certificado de Voluntariado',
      'actividad_titulo': 'Censo de Aves y Reforestación',
      'horas': 6,
      'fecha_emision': '2026-08-28',
      'estado': 'en_proceso',
      'codigo_verificacion': 'FB-VOL-2026-PEND',
      'firmado_por': 'En revisión por coordinación',
      'destinatario': 'Luis Fernando Pérez Gómez',
      'documento_identidad': '1.098.765.432',
    },
  ];

  static const List<Map<String, dynamic>> sampleBadges = [
    {
      'id': 'badge-01',
      'nombre': 'Primeros pasos',
      'descripcion': 'Completar 1 actividad con tracking activo',
      'icono': 'directions_walk',
      'obtenida': true,
      'fecha_obtenida': '2026-08-15',
      'categoria': 'Esfuerzo Físico',
    },
    {
      'id': 'badge-02',
      'nombre': 'Caminante constante',
      'descripcion': '3 actividades seguidas con +2.000 pasos',
      'icono': 'nordic_walking',
      'obtenida': true,
      'fecha_obtenida': '2026-08-28',
      'categoria': 'Esfuerzo Físico',
    },
    {
      'id': 'badge-03',
      'nombre': 'Jornada intensa',
      'descripcion': 'Superar 8.000 pasos en una sola actividad',
      'icono': 'local_fire_department',
      'obtenida': false,
      'fecha_obtenida': null,
      'categoria': 'Esfuerzo Físico',
    },
    {
      'id': 'badge-04',
      'nombre': 'Top del mes',
      'descripcion': 'Mayor promedio de pasos por actividad ese mes',
      'icono': 'emoji_events',
      'obtenida': false,
      'fecha_obtenida': null,
      'categoria': 'Liderazgo',
    },
    {
      'id': 'badge-05',
      'nombre': 'Guardián del Bosque',
      'descripcion': 'Plantar más de 10 árboles en jornadas de reforestación',
      'icono': 'forest',
      'obtenida': true,
      'fecha_obtenida': '2026-08-15',
      'categoria': 'Impacto Ambiental',
    },
  ];
}
